"""i

Revision ID: e804a003a382
Revises: 
Create Date: 2023-03-15 09:22:37.211970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e804a003a382'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cons_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cons_data_id'), 'cons_data', ['id'], unique=False)
    op.create_table('news_title',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.create_index('data_title_date_unique_1',
                    'news_title',
                    [sa.text("((data->>'title')::text)"),
                     sa.text("(substring((data->>'time')::text, 1, 10))")],
                    unique=True)

    op.create_index('data_href_date_unique_1',
                    'news_title',
                    [sa.text("((data->>'href')::text)"),
                     sa.text("(substring((data->>'time')::text, 1, 10))")],
                    unique=True)


def downgrade() -> None:
    op.drop_index(op.f('data_href_date_unique_1'), table_name='news_title')
    op.drop_index(op.f('data_title_date_unique_1'), table_name='news_title')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_title')
    op.drop_index(op.f('ix_cons_data_id'), table_name='cons_data')
    op.drop_table('cons_data')
    # ### end Alembic commands ###
