name: nlp
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services: 
      test_db:
        image: postgres:15.1-alpine
        ports: 
          - "5432:5432"
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
    env:
      POSTGRES_HOST: test_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
      TEST_DATABASE_URL: "postgresql://test:test@localhost:5432/test_db"
      DATABASE_URL: "postgresql://test:test@localhost:5432/test_db"
      PYTHONPATH: ./src
    
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - 
        name: Lint with flake8
        run: |
          pip install flake8
          flake8 --ignore=E501,E122,W503 --exclude=src/test_db src
      - 
        name: Setup alembic migrations
        run: | 
          pip install alembic
          alembic -c "alembic-test.ci.ini" upgrade head
        working-directory: ./src
      - 
        name: Testing with pytest
        run: | 
          pytest .
