name: nlp
on:
  workflow_call:
    secrets:
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true
jobs:
  call_test_workflow:
    name: lint and test
    uses: ./.github/workflows/test.yml
  pull:
    needs: call_test_workflow
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.dockerhub-username }}/newsmakers-nlp:latest
