name: nlp
on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        description: 'Docker username for login'
        required: true
      DOCKERHUB_TOKEN:
        description: 'Dockerhub password token for login'
        required: true
jobs:
  call_test_workflow:
    uses: ./.github/workflows/test.yml
  pull:
    needs: call_test_workflow
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/newsmakers-nlp:latest
